In [2]:
import numpy as np

m = np.load('575072 DJ Fresh feat Rita Ora - Hot Right Now (Radio Edit) Input.npy')
print(m)

[[-30.15091  -29.725418 -29.114286 ... -26.695147 -26.498777 -26.0303  ]
 [-24.38112  -26.904966 -27.691614 ... -25.55507  -25.011137 -24.69913 ]
 [ -6.674835  -5.888514  -7.757381 ... -20.066954 -20.563728 -21.295492]
 ...
 [-13.543145  -8.852234  -8.652678 ... -11.606364 -13.175977 -12.391448]
 [ -9.648139  -9.830494 -10.277636 ... -12.039638 -13.2328   -12.482591]
 [ -9.101287  -9.897528 -11.693384 ... -12.181663 -13.251795 -12.294388]]
